name: Dean
favicon: null
layout_spectrum: 0.49299
typography_spectrum: 0.31918
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Thoughts and Miscellany
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9660ff'
    - '#170e21'
    - '#7ba2ff'
    - '#79808d'
  brandStrength: 0.8319011
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
