name: Dean
favicon: null
layout_spectrum: 0.9908701
typography_spectrum: 0.6503759
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060501'
    - '#FFFFFF'
    - '#9B9199'
    - '#FF9100'
    - '#FFDE88'
  brandStrength: 0.8319011
  lightness: 0.2593985
  saturation: 0.8029001
  rhythmicContrast: 1
purpose: []
